import Link from "next/link";
import { Mark, Tagline } from "./_components/lockup";
import { Reveal } from "./_components/reveal";
import { SiteFooter, SiteHeader } from "./_components/site-chrome";
import { Converge, Held, KeyField, Strata } from "./_components/scenes";
import { ApprovalLifecycle, AuditTable, EnvelopeSample, Pipeline, Verdicts } from "./_components/proof";

function Arrow() {
  return (
    <svg width="24" height="9" viewBox="0 0 24 9" fill="none" aria-hidden>
      <path d="M0 4.5h22M18 1l4 3.5L18 8" stroke="currentColor" strokeWidth="1.1" />
    </svg>
  );
}

/**
 * The homepage follows the section rhythm the sibling 2600i property already
 * uses — full-height hero, a single large mission statement, then alternating
 * full-bleed sections. Only the subject changes: the frontier here is what one
 * agent is allowed to do to another system.
 *
 * Every claim below is either an architectural statement or a value read out of
 * data/gateway-trace.json, which is generated by running the real Gateway.
 * There are no customers, usage figures, certifications or partners on this
 * page because there are none to report.
 */
export default function Home() {
  return (
    <div className="sx" id="top">
      <SiteHeader />

      <main>
        {/* --- HERO -------------------------------------------------------- */}
        <section className="sx-hero">
          <div className="scene scene-dawn" aria-hidden>
            <KeyField />
            <div className="scene-vignette scene-vignette--left" />
            <div className="scene-vignette scene-vignette--bottom" />
          </div>

          <div className="sx-inner">
            <Reveal className="sx-block">
              <Mark className="sx-hero-mark" />
              <Tagline>Identity. Authority. Trust.</Tagline>
              <h1 className="sx-h1">The trust layer for AI agents</h1>
              <p className="sx-copy">
                Agents are starting to act on real systems — buying, scheduling, querying, changing
                things. AIMTP is the open protocol for proving who is asking, on whose authority,
                and within what limits.
              </p>
              <div className="sx-btn-row">
                <Link href="/gateway" className="sx-btn">
                  See the Gateway
                  <Arrow />
                </Link>
                <Link href="/protocol" className="sx-btn sx-btn--ghost">
                  Read the protocol
                  <Arrow />
                </Link>
              </div>
            </Reveal>
          </div>
        </section>

        {/* --- MISSION ----------------------------------------------------- */}
        <section className="sx-section sx-section--left" id="mission">
          <div className="scene scene-orb" aria-hidden />

          <div className="sx-inner">
            <Reveal className="sx-block">
              <h2 className="sx-h2 sx-h2--xl">SMTP moved messages. AIMTP moves authority.</h2>
              <p className="sx-copy">
                Mail worked because everyone agreed on an envelope. Agent-to-agent traffic needs the
                same agreement about more than content: the intent behind a request, the identity
                making it, the authority it carries, the constraints it must respect, and the
                evidence it leaves behind.
              </p>
              <Link href="/protocol" className="sx-btn">
                The envelope
                <Arrow />
              </Link>
            </Reveal>
          </div>
        </section>

        {/* --- THE GATEWAY ------------------------------------------------- */}
        <section className="sx-section sx-section--left" id="gateway">
          <div className="scene scene-gate" aria-hidden>
            <Converge />
            <div className="scene-vignette scene-vignette--left" />
          </div>

          <div className="sx-inner">
            <Reveal className="sx-block">
              <span className="sx-eyebrow">Agent Trust Gateway</span>
              <h2 className="sx-h2 sx-h2--tight">Every agent request, interrogated</h2>
              <Tagline>Verify. Authorize. Act.</Tagline>
              <p className="sx-copy">
                The Gateway sits between an external agent and a protected system and answers the
                same questions every time, in the same order — before anything executes.
              </p>
              <Link href="/gateway" className="sx-btn">
                How it works
                <Arrow />
              </Link>
            </Reveal>
          </div>
        </section>

        {/* --- THE PIPELINE ------------------------------------------------ */}
        <section className="sx-section sx-section--wide" id="pipeline">
          <div className="scene scene-spec" aria-hidden />

          <div className="sx-inner">
            <Reveal>
              <span className="sx-eyebrow">Order of operations</span>
              <h2 className="sx-h2 sx-h2--tight">Policy is the last question, not the first</h2>
              <p className="sx-copy">
                Authorization is meaningless if identity was never established. Each stage runs
                before the protected action is reachable, and a failure at any of them ends the
                request there.
              </p>
              <div style={{ marginTop: 40, maxWidth: 760 }}>
                <Pipeline />
              </div>
              <EnvelopeSample />
            </Reveal>
          </div>
        </section>

        {/* --- THE DECISION ------------------------------------------------ */}
        <section className="sx-section sx-section--wide" id="decisions">
          <div className="scene scene-verdict" aria-hidden />

          <div className="sx-inner">
            <Reveal>
              <span className="sx-eyebrow">The decision</span>
              <h2 className="sx-h2 sx-h2--tight">Three answers. No ambiguity.</h2>
              <p className="sx-copy">
                Every request resolves to exactly one of three outcomes, and the reason is recorded
                alongside it. The reasons below are the Gateway&rsquo;s own, read out of a recorded
                run.
              </p>
              <Verdicts />
            </Reveal>
          </div>
        </section>

        {/* --- HUMAN APPROVAL ---------------------------------------------- */}
        <section className="sx-section sx-section--right" id="approval">
          <div className="scene scene-hold" aria-hidden>
            <Held />
            <div className="scene-vignette scene-vignette--right" />
          </div>

          <div className="sx-inner">
            <Reveal className="sx-block">
              <span className="sx-eyebrow">Human approval</span>
              <h2 className="sx-h2 sx-h2--tight">Some things should wait for a person</h2>
              <p className="sx-copy">
                An agent asking to spend $25 is not the same as one asking to spend $10,000. Over a
                threshold, the request is held as a pending record and nothing executes until an
                operator decides — and the record can only ever be claimed once.
              </p>
              <div style={{ marginTop: 34 }}>
                <ApprovalLifecycle />
              </div>
            </Reveal>
          </div>
        </section>

        {/* --- AUDIT -------------------------------------------------------- */}
        <section className="sx-section sx-section--wide" id="audit">
          <div className="scene scene-ledger" aria-hidden>
            <Strata />
            <div className="scene-scrim" />
          </div>

          <div className="sx-inner">
            <Reveal>
              <span className="sx-eyebrow">Evidence</span>
              <h2 className="sx-h2 sx-h2--tight">Every decision leaves a record</h2>
              <p className="sx-copy">
                Allowed, denied, held, approved, rejected, replayed — each one is appended with the
                authentication result, the trust result, the policy decision and the reason. The
                authorization is written before the action runs, so a failure downstream still
                leaves a complete trail.
              </p>
              <AuditTable />
            </Reveal>
          </div>
        </section>

        {/* --- THE PROTOCOL ------------------------------------------------- */}
        <section className="sx-section sx-section--left" id="protocol">
          <div className="scene scene-spec" aria-hidden>
            <div className="scene-vignette scene-vignette--left" />
          </div>

          <div className="sx-inner">
            <Reveal className="sx-block">
              <span className="sx-eyebrow">The protocol underneath</span>
              <h2 className="sx-h2 sx-h2--tight">Frozen wire. Verified bytes.</h2>
              <p className="sx-copy">
                The Gateway is one enforcement point built on AIMTP, not the whole of it. The wire
                version is frozen at <span className="mono">aimtp/0.1</span> and the canonical
                signing payload is pinned by committed conformance vectors — so two independent
                implementations either agree byte-for-byte or fail the suite.
              </p>
              <Link href="/protocol" className="sx-btn">
                Conformance
                <Arrow />
              </Link>
            </Reveal>
          </div>
        </section>

        {/* --- BUILD -------------------------------------------------------- */}
        <section className="sx-section sx-section--right" id="build">
          <div className="scene scene-dawn" aria-hidden>
            <div className="scene-vignette scene-vignette--right" />
          </div>

          <div className="sx-inner">
            <Reveal className="sx-block">
              <span className="sx-eyebrow">Developer preview</span>
              <h2 className="sx-h2 sx-h2--tight">Start with the Gateway</h2>
              <p className="sx-copy">
                Run it locally against a demo policy, watch the decisions land, and read the audit
                trail it produces. No account, no key exchange, nothing hosted.
              </p>
              <div className="sx-btn-row">
                <Link href="/demo" className="sx-btn">
                  Run the demo
                  <Arrow />
                </Link>
                <Link href="/docs" className="sx-btn sx-btn--ghost">
                  Documentation
                  <Arrow />
                </Link>
              </div>
            </Reveal>
          </div>
        </section>
      </main>

      <SiteFooter />
    </div>
  );
}
